app:
  name: "KSWI Backend"
  version: "1.0.0"
  environment: "development"
  debug: true

server:
  host: "localhost"
  port: 8080
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 60

database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "your_password"
  database: "kswi_db"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 300

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  max_retries: 3
  pool_size: 10
  min_idle_conn: 5

jwt:
  secret: "your-super-secret-jwt-key-change-this-in-production"
  access_token_ttl: 3600    # 1 hour in seconds
  refresh_token_ttl: 604800 # 7 days in seconds
  issuer: "kswi-backend"

log:
  level: "info"      # debug, info, warn, error
  format: "json"     # json, text
  output: "stdout"   # stdout, stderr, file